version: '3.8'
services:
  portfolio-db:
    image: postgres:15-alpine
    container_name: portfolio-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: portfolio_db
    volumes:
      - portfolio_pg_data:/var/lib/postgresql/data
    networks:
      - portfolio-net

  portfolio-app:
    build: .
    container_name: portfolio-app
    restart: unless-stopped
    environment:
      - DB_USER=portfolio_user
      - DB_HOST=portfolio-db
      - DB_NAME=portfolio_db
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - RESEND_API_KEY=${RESEND_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
    depends_on:
      - portfolio-db
    networks:
      - portfolio-net
      - proxy-tier

volumes:
  portfolio_pg_data:

networks:
  portfolio-net:
  proxy-tier:
    external: true
